import java.awt.*;
import java.io.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class SaveLoad extends javax.swing.JPanel {

    private Image img = new ImageIcon("source/img.jpg").getImage();
    
    public SaveLoad() {
        initComponents();
    }
    
    public void paintComponent(Graphics g)
    {
        BoardGUI.status.setText("Save and/or load Game of Loyalty games.");
        g.setColor(Color.black);
        g.fillRect(0,0,getWidth(),getHeight());
        g.drawImage(img,0,44,this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(589, 505));
        setMinimumSize(new java.awt.Dimension(589, 505));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Save current game to disk:");

        jButton1.setMnemonic('S');
        jButton1.setText("Save...");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Load saved game from disk:");

        jButton2.setMnemonic('L');
        jButton2.setText("Load...");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(142, 142, 142))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 437, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogType(JFileChooser.SAVE_DIALOG);
        File f = new File(".");
        try
        {
            int val = chooser.showSaveDialog(null);
            if(val == JFileChooser.APPROVE_OPTION)
                f = chooser.getSelectedFile();
            FileOutputStream fos = new FileOutputStream(f);
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            fos.write(1);
            oos.writeObject(BoardGUI.gui.board);
            oos.writeObject(Arbiter.isWin);
            oos.writeObject(BoardGUI.aiDiff);
            oos.writeObject(BoardGUI.Egames);
            oos.writeObject(BoardGUI.EgamesWon);
            oos.writeObject(BoardGUI.Mgames);
            oos.writeObject(BoardGUI.MgamesWon);
            oos.writeObject(BoardGUI.Dgames);
            oos.writeObject(BoardGUI.DgamesWon);
            oos.writeObject(BoardGUI.gui.moves);
            oos.close();
            JOptionPane.showMessageDialog(null,String.format("%s has been saved successfully.",f.getName()),"Load game",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception ex){JOptionPane.showMessageDialog(null,ex.toString(),"Error!",JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogType(JFileChooser.OPEN_DIALOG);
        File f = new File(".");
        try
        {
            int val = chooser.showOpenDialog(null);
            if(val == JFileChooser.APPROVE_OPTION)
                f = chooser.getSelectedFile();
            FileInputStream fis = new FileInputStream(f); 
            ObjectInputStream ois = new ObjectInputStream(fis);
            for (int i = fis.read(); i > 0; i--) 
            {
                Object obk = ois.readObject();
                BoardGUI.gui.board = (Piece[][]) obk;
                Object obl = ois.readObject();
                Arbiter.isWin = (boolean) obl;
                Object obj = ois.readObject();
                BoardGUI.aiDiff = (int) obj;
                Object obm = ois.readObject();
                BoardGUI.Egames = (int) obm;
                Object obn = ois.readObject();
                BoardGUI.EgamesWon = (int) obn;
                Object obo = ois.readObject();
                BoardGUI.Mgames = (int) obo;
                Object obp = ois.readObject();
                BoardGUI.MgamesWon = (int) obp;
                Object obq = ois.readObject();
                BoardGUI.Dgames = (int) obq;
                Object obr = ois.readObject();
                BoardGUI.DgamesWon = (int) obr;
                Object obs = ois.readObject();
                BoardGUI.gui.moves = (int) obs;
            }
            BoardGUI.gui.clear();
            BoardGUI.set.clear();
            BoardGUI.st.clear();
            JOptionPane.showMessageDialog(null,String.format("%s has been loaded successfully.",f.getName()),"Load game",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){JOptionPane.showMessageDialog(null, e.toString(),"Error!", WIDTH);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
